### PR TITLE
EOS-18303: Failhard: Stop immediately on component config failure

### PR DESCRIPTION
**Pull request by ypise**
------------------------------------------------
Failhard: the minions to stop immediately
after the first failure detected

Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

### CODE REVIEW

**Review by nitin-seagate — APPROVED** [review]
Looks good to me...

**Review by andkononykhin2 — COMMENTED** [review]
@ypise we haven't work in that manner and I am not sure how clear a failure would be: I guess it would be harder to understand what actually failed since salt will mark as failed not only a failure but also not yet checked/run states.

I believe salt [doesn't recommend](https://docs.saltproject.io/en/latest/ref/states/failhard.html#global-failhard) that mode by similar reason.

**Comment by ypise** [comment]
> @ypise we haven't work in that manner and I am not sure how clear a failure would be: I guess it would be harder to understand what actually failed since salt will mark as failed not only a failure but also not yet checked/run states.
> 
> I believe salt [doesn't recommend](https://docs.saltproject.io/en/latest/ref/states/failhard.html#global-failhard) that mode by similar reason.

I agree, which is why we had not enabled it.
However, for mini-provisioner they want the flow to break immediately.
May be we can set it back to `False` in future once mini-provisioner has stabilized for all components.

@andkononykhin2 what's your opinion?

**Review by 83bhp — APPROVED** [review]

**Comment by andkononykhin2** [comment]
> > @ypise we haven't work in that manner and I am not sure how clear a failure would be: I guess it would be harder to understand what actually failed since salt will mark as failed not only a failure but also not yet checked/run states.
> > I believe salt [doesn't recommend](https://docs.saltproject.io/en/latest/ref/states/failhard.html#global-failhard) that mode by similar reason.
> 
> I agree, which is why we had not enabled it.
> However, for mini-provisioner they want the flow to break immediately.
> May be we can set it back to `False` in future once mini-provisioner has stabilized for all components.
> 
> @andkononykhin2 what's your opinion?

I think [state level option](https://docs.saltproject.io/en/latest/ref/states/failhard.html#state-level-failhard) might be a good alternative. For sure it would require some more changes and copy-pastes. Possibly we can consider to use Jinja macros to make that easier to do in future.

**Comment by andkononykhin2** [comment]
[our tip for Jinja macros](https://github.com/Seagate/cortx-prvsnr/blob/pre-cortx-1.0/docs/saltstack.md#jinja-macros---sharing-the-logic-in-sls)

**Comment by ypise** [comment]
> > > @ypise we haven't work in that manner and I am not sure how clear a failure would be: I guess it would be harder to understand what actually failed since salt will mark as failed not only a failure but also not yet checked/run states.
> > > I believe salt [doesn't recommend](https://docs.saltproject.io/en/latest/ref/states/failhard.html#global-failhard) that mode by similar reason.
> > 
> > 
> > I agree, which is why we had not enabled it.
> > However, for mini-provisioner they want the flow to break immediately.
> > May be we can set it back to `False` in future once mini-provisioner has stabilized for all components.
> > @andkononykhin2 what's your opinion?
> 
> I think [state level option](https://docs.saltproject.io/en/latest/ref/states/failhard.html#state-level-failhard) might be a good alternative. For sure it would require some more changes and copy-pastes. Possibly we can consider to use Jinja macros to make that easier to do in future.

Done. This seems to be a better option.
We soon would need to implement the macro based deployments. Problem is we might lost granular control over the deployments over CLI.

**Pull request merged**
