### PR TITLE
Main Candidate 280521

### PR DESCRIPTION
**Pull request by ypise**
Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

-----------------------------------------------------------------------
Commits for landing:
- EOS-20662: Field Prepare: Firewall Configuration (#1288)
- hide unwanted cache logs from salt-ssh (#1291)
- EOS-20793: check presence of all /etc files before deleting (#1303)
- [EOS-20668] Added cluster show , create and network config commands (#1284)
- [SW-Upgrade][Fix]: I prepare the fix and improvements of the set of SW upgrade commands: I made them more failure tolerant (#1307)
- EOS-20659: Field Prepare: Time configuration using cortx_setup cli command (#1287)
- EOS-20658:Temporary assignment of Management VIP to Salt Minion during Field Prepare (#1289)
- EOS-19898: LR Signature module integrated with CLI (#1283)
- EOS-19896: Factory - Configure storage enclosure (#1308)
- EOS-20664: Field Prepare: Network-Configuration (#1300)
- EOS-20662: Field prepare Firewall configuration- debug logs added (#1309)
- EOS-20862: Enclosure_id configuration (#1313)
- Fix to the Vagrantfile (#1304)
- EOS-20862: Enclosure_id configuration fixes
- EOS-19569: Removed occurances of contiguous term (#1311)
- EOS-20667: Field API for Storageset (#1293)
- EOS-20657: Implement gpg verification for an ISO as alternative to hash based approach (#1310)
- Improvement - Network configuration and prepare (#1316)
- EOS-20665: Field Prepare - Storage configuration (#1315)

### CODE REVIEW

**Comment by ypise** [comment]
test this please

**Comment by ypise** [comment]
test this please

**Review by andkononykhin2 — APPROVED** [review]

**Review by 83bhp — APPROVED** [review]

**Comment by ypise** [comment]
test this please

**Comment by ypise** [comment]
The single node VM deployment is green with custom build:
http://eos-jenkins.colo.seagate.com/job/Provisioner/job/Single-Node-VM-Deploy/350/

**Pull request merged**
