### PR TITLE
CORTX-27923 - Upgrade aiohttp from version 3.6.1 to 3.8.1

### PR DESCRIPTION
**Pull request by swanand-gadre**
# Problem Statement
- Problem statement

Upgrade aiohttp version from 3.6.1 to 3.8.1
This upgrade is expected to resolve security vulnerabilities.

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

This fix require changes in python_requirement.txt file to upgrade library version from 3.6.1 to 3.8.1
Corresponding story is - https://jts.seagate.com/browse/CORTX-27923

# Coding
   Checklist for Author
-  [X] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [X] Unit and System Tests are added
- [X] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [X] Testing was performed with RPM

All the test details are documented. Corresponding document is attached to -> https://jts.seagate.com/browse/CORTX-27923

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [X] JIRA number/GitHub Issue added to PR
- [X] PR is self reviewed
- [X] Jira and state/status is updated and JIRA is updated with PR link
- [X] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

No documentation updates

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by swanand-gadre** [comment]
**Please don't merge this PR directly.
As it has dependencies over multiple components
This PR will be merged in coordinated manner in a meeting by calling all component gatekeepers**

**Review by tanujashinde0405 — APPROVED** [review]

**Review by kailashyadav11 — APPROVED** [review]
LGTM

**Review by nitin-seagate — APPROVED** [review]
LGTM

**Comment by kailashyadav11** [comment]
ok to test

**Pull request merged**
