### PR TITLE
EOS-10911:Move all configs except common configs out of provisioner to /etc/sspl.conf

### PR DESCRIPTION
**Pull request by shubhamseagate**

### CODE REVIEW

**Comment by ypise** [comment]
@shubhamseagate 
The commit and PR message has to be very clear.
Also ensure all your commits in this PR are signed.

**Review by andkononykhin2 — APPROVED** [review]

**Review by ypise — APPROVED** [review]

**Comment by ypise** [comment]
@shubhamseagate 
You need to fix these in your commits:
```
Commit sha: b1cc42b, Author: Shubham Bhosale, Committer: Shubham Bhosale; Expected "Shubham Bhosale shubham.bhosale@seagate.com", but got "root root@ssc-vm-c-0666.colo.seagate.com".
Commit sha: 3ce1433, Author: Shubham Bhosale, Committer: Shubham Bhosale; Expected "Shubham Bhosale shubham.bhosale@seagate.com", but got "root root@ssc-vm-c-0666.colo.seagate.com".
```
**root root@ssc-vm-c-0666.colo.seagate.com** not acceptable.

**Review by ypise — CHANGES_REQUESTED** [review]
@shubhamseagate 
You need to fix these in your commits:
```
Commit sha: b1cc42b, Author: Shubham Bhosale, Committer: Shubham Bhosale; Expected "Shubham Bhosale shubham.bhosale@seagate.com", but got "root root@ssc-vm-c-0666.colo.seagate.com".
Commit sha: 3ce1433, Author: Shubham Bhosale, Committer: Shubham Bhosale; Expected "Shubham Bhosale shubham.bhosale@seagate.com", but got "root root@ssc-vm-c-0666.colo.seagate.com".
```
**root root@ssc-vm-c-0666.colo.seagate.com** not acceptable.

**Review by cdeshmukh — APPROVED** [review]

**Review by sandeepsgt — APPROVED** [review]

**Review by cdeshmukh — APPROVED** [review]

**Review by ypise — APPROVED** [review]

**Comment by ypise** [comment]
@cdeshmukh, @saurabhkhanvilkar 
Do we still want this PR merged?
This was put on hold due to the code freeze, but can land into main branch now, if requried.

**Comment by cdeshmukh** [comment]
> @cdeshmukh, @saurabhkhanvilkar
> Do we still want this PR merged?
> This was put on hold due to the code freeze, but can land into main branch now, if required.

@ypise  yes lets clean it up.
@mariyappanp as you are doing relevant changes in sspl, please review/suggest and drive this to closure as required.

**Comment by ypise** [comment]
No more relevant with new mini-provisioner design.

**Pull request closed without merging**
