### PR TITLE
EOS:27327: changed secrets path variable name

### PR DESCRIPTION
**Pull request by lakshita-jain**
Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>

# Problem Statement
- Updated provisioner.py for secrets path variable name 

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [x] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [x] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [x] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by tanujashinde0405 — CHANGES_REQUESTED** [review]
Please make sure deployment is working and post deployment results here.
Also make sure with custom path secrets are getting picked up now from custom path.

**Review by kailashyadav11 — APPROVED** [review]
LGTM, can be merged if deployment goes fine.

**Comment by lakshita-jain** [comment]
deployment with edited latest image successful:

^C[root@ssc-vm-g2-rhev4-3005 ~]# kubectl get po
NAME                                                 READY   STATUS    RESTARTS   AGE
consul-8f7sk                                         1/1     Running   0          21m
consul-pdmwl                                         1/1     Running   0          21m
consul-server-0                                      1/1     Running   0          19m
consul-server-1                                      1/1     Running   0          20m
consul-server-2                                      1/1     Running   0          21m
consul-tb6jl                                         1/1     Running   0          21m
cortx-control-58b8c76976-pg2b2                       4/4     Running   0          18m
cortx-data-ssc-vm-g2-rhev4-3005-67f9f6d9c9-6p96b     4/4     Running   0          17m
cortx-data-ssc-vm-g2-rhev4-3007-5cdbcbc99c-p6tlf     4/4     Running   0          17m
cortx-data-ssc-vm-g2-rhev4-3008-79bf5bdd7d-sth42     4/4     Running   0          17m
cortx-ha-77db54c8cf-dht6w                            3/3     Running   0          12m
cortx-server-ssc-vm-g2-rhev4-3005-84cf895598-627lv   6/6     Running   0          14m
cortx-server-ssc-vm-g2-rhev4-3007-86964c899d-wf4z6   6/6     Running   0          14m
cortx-server-ssc-vm-g2-rhev4-3008-5fc94df8bd-cwrn8   6/6     Running   0          14m
kafka-0                                              1/1     Running   0          19m
kafka-1                                              1/1     Running   0          19m
kafka-2                                              1/1     Running   0          19m
openldap-0                                           1/1     Running   0          21m
openldap-1                                           1/1     Running   0          20m
openldap-2                                           1/1     Running   0          20m
zookeeper-0                                          1/1     Running   0          20m
zookeeper-1                                          1/1     Running   0          20m
zookeeper-2                                          1/1     Running   0          20m


[root@cortx-data-headless-svc-ssc-vm-g2-rhev4-3005 /]# hctl status
Data pool:
    # fid name
    0x6f00000000000001:0x9c 'storage-set-1__sns'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0xdb 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
    cortx-data-headless-svc-ssc-vm-g2-rhev4-3005
    [started]  hax        0x7200000000000001:0x2f  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3005@2001
    [started]  ioservice  0x7200000000000001:0x32  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3005@3001
    [started]  ioservice  0x7200000000000001:0x41  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3005@3002
    [started]  confd      0x7200000000000001:0x50  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3005@3003
    cortx-data-headless-svc-ssc-vm-g2-rhev4-3007  (RC)
    [started]  hax        0x7200000000000001:0x7   inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3007@2001
    [started]  ioservice  0x7200000000000001:0xa   inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3007@3001
    [started]  ioservice  0x7200000000000001:0x19  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3007@3002
    [started]  confd      0x7200000000000001:0x28  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3007@3003
    cortx-data-headless-svc-ssc-vm-g2-rhev4-3008
    [started]  hax        0x7200000000000001:0x57  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3008@2001
    [started]  ioservice  0x7200000000000001:0x5a  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3008@3001
    [started]  ioservice  0x7200000000000001:0x69  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3008@3002
    [started]  confd      0x7200000000000001:0x78  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-3008@3003
    cortx-server-headless-svc-ssc-vm-g2-rhev4-3005
    [started]  hax        0x7200000000000001:0x7d  inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-3005@2001
    [started]  s3server   0x7200000000000001:0x80  inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-3005@4001
    [started]  s3server   0x7200000000000001:0x83  inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-3005@4002
    cortx-server-headless-svc-ssc-vm-g2-rhev4-3008
    [started]  hax        0x7200000000000001:0x88  inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-3008@2001
    [started]  s3server   0x7200000000000001:0x8b  inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-3008@4001
    [started]  s3server   0x7200000000000001:0x8e  inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-3008@4002
    cortx-server-headless-svc-ssc-vm-g2-rhev4-3007
    [started]  hax        0x7200000000000001:0x93  inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-3007@2001
    [started]  s3server   0x7200000000000001:0x96  inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-3007@4001
    [started]  s3server   0x7200000000000001:0x99  inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-3007@4002

**Comment by lakshita-jain** [comment]
Tested with custom path, the confstore is created in the testpath and the secrets are correct and verified after decryption.

[root@cortx-control-headless-svc /]# cd /etc/testpath/
[root@cortx-control-headless-svc testpath]# ls
cluster.conf  csm  log  motr  s3  solution  utils

[root@cortx-control-headless-svc /]# python3 -W "ignore" -c "from cortx.utils.security.cipher import Cipher; key = Cipher.generate_key('eccbe753f1c84b0ca43debc5e7167b6a','cortx');print((Cipher.decrypt(key, b'gAAAAABh3XPwYc5-V8YObwr6BJMl-HO9X1sEtVr8enWy48AaGaOiDHR1boa3mZEBH3LAlszb_f-siERZgqMtEI55nc0HXe41Ng==')).decode('utf-8'))"
seagate1
[root@cortx-control-headless-svc /]# vi /etc/testpath/cluster.conf
[root@cortx-control-headless-svc /]# python3 -W "ignore" -c "from cortx.utils.security.cipher import Cipher; key = Cipher.generate_key('eccbe753f1c84b0ca43debc5e7167b6a','cortx');print((Cipher.decrypt(key, b'gAAAAABh3XPw0eZLmxJsDIi2k6444ldzxQhH8WC5Absg1-pJnKlob_P5_h0Jox1yuCMD2j97A9fc5WClP_AP3h84lL8Dkjud_w==')).decode('utf-8'))"
seagate2
[root@cortx-control-headless-svc /]# vi /etc/testpath/cluster.conf
[root@cortx-control-headless-svc /]# python3 -W "ignore" -c "from cortx.utils.security.cipher import Cipher; key = Cipher.generate_key('eccbe753f1c84b0ca43debc5e7167b6a','cortx');print((Cipher.decrypt(key, b'gAAAAABh3XPw7RazGIeG16llp25iLjwv-cZNqPeTZk3-i6YwUkVL9orcO60UEKck1vnOLU7kx1cpw6iDCEjoXEVTLfnobxoQSg==')).decode('utf-8'))"
Cortxadmin@123
[root@cortx-control-headless-svc /]#

**Review by tanujashinde0405 — APPROVED** [review]

**Pull request merged**
