### PR TITLE
CORTX-30259: fix codacy dashboard issues

### PR DESCRIPTION
**Pull request by tanujashinde0405**
Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>

# Problem Statement

fix codacy dashboard issues

## Design

fix codacy dashboard issues

## Coding

Checklist for Author

*   \[x] Coding conventions are followed and code is consistent

## Testing

Checklist for Author

*   \[ ] Unit and System Tests are added
*   \[x] Test Cases cover Happy Path, Non-Happy Path and Scalability
*   \[x] Testing was performed with RPM

## Impact Analysis

Checklist for Author/Reviewer/GateKeeper

*   \[ ] Interface change (if any) are documented
*   \[ ] Side effects on other features (deployment/upgrade)
*   \[ ] Dependencies on other component(s)

## Review Checklist

Checklist for Author

*   \[x] JIRA number/GitHub Issue added to PR
*   \[x] PR is self reviewed
*   \[x] Jira and state/status is updated and JIRA is updated with PR link
*   \[x] Check if the description is clear and explained

## Documentation

Checklist for Author

*   \[ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Review by tanujashinde0405 — COMMENTED** [review]
retest this please

**Review by tanujashinde0405 — COMMENTED** [review]
retest this please

**Review by nitin-seagate — APPROVED** [review]
LGTM

**Review by tanujashinde0405 — COMMENTED** [review]
retest this please

**Comment by gauravchaudhari02** [comment]
retest this please

**Pull request merged**
