### PR TITLE
EOS-23430: cortx_setup node finalize command failed on 3 node VM depl…

### PR DESCRIPTION
**Pull request by tanujashinde0405**
…oyment.

Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by 83bhp — APPROVED** [review]

**Review by nitin-seagate — CHANGES_REQUESTED** [review]
Why do we fetch machine-id and enclosure-id to decide if the environment is HW or VM...
Please fetch server-type whether its HW or VM

**Review by SomwanshiAnjali — APPROVED** [review]

**Review by nitin-seagate — APPROVED** [review]
Approved
@cdeshmukh @mariyappanp Ideally we should have health check for VM as well right?

**Comment by cdeshmukh** [comment]
Yes, Health check on VM would be there, just that it wont return any data for hw resources. I believe we had tested this scenario too, @mariyappanp ?

**Comment by mariyappanp** [comment]
> Yes, Health check on VM would be there, just that it wont return any data for hw resources. I believe we had tested this scenario too, @mariyappanp ?

**Yes**

**Pull request merged**
