### PR TITLE
EOS-23141 : updated confstore keys for s3 requirements (#5996)

### PR DESCRIPTION
**Pull request by 83bhp**
Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by 83bhp** [comment]
run vm-deployment

**Comment by priyankdal** [comment]
ok to test

**Comment by priyankdal** [comment]
run vm-deployment

**Pull request merged**
