### PR TITLE
 CORTX-30252: Docstring Codacy errors resolution

### PR DESCRIPTION
**Pull request by lakshita-jain**
Currently making Docstring related codacy error resolution
changes in the 4 files.
Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-   [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-   [ ] Unit and System Tests are added
-   [x] Test Cases cover Happy Path, Non-Happy Path and Scalability
-   [x] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-   [ ] Interface change (if any) are documented
-   [ ] Side effects on other features (deployment/upgrade)
-   [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
-   [x] JIRA number/GitHub Issue added to PR
-   [x] PR is self reviewed
-   [x] Jira and state/status is updated and JIRA is updated with PR link
-   [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
-   [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by tanujashinde0405 — CHANGES_REQUESTED** [review]
Please resolve codacy warnings

**Review by kailashyadav11 — APPROVED** [review]

**Review by tanujashinde0405 — APPROVED** [review]

**Comment by kailashyadav11** [comment]
retest this please

**Review by nitin-seagate — APPROVED** [review]
LGTM

**Comment by lakshita-jain** [comment]
retest this please

**Comment by kailashyadav11** [comment]
retest this please

**Comment by gauravchaudhari02** [comment]
retest this please

**Pull request merged**
