### PR TITLE
Cortx 29589: Removal of redundant keys storage_set_count & cvg_count

### PR DESCRIPTION
**Pull request by lakshita-jain**
# Problem Statement
- config-store has 2 redundant keys 'cvg_count' and 'storage_set_count'

# Design
-  remove cvg_count and storage_set_count from prvisioner's code

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalabili
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [x] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [x] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by kailashyadav11** [comment]
fill in the PR  template please

**Review by tanujashinde0405 — APPROVED** [review]

**Review by nitin-seagate — APPROVED** [review]
LGTM

**Review by tanujashinde0405 — COMMENTED** [review]
retest this please

**Review by tanujashinde0405 — COMMENTED** [review]
ok to test

**Comment by lakshita-jain** [comment]
3N deployment successful
NAME                                                 READY   STATUS    RESTARTS   AGE
consul-client-d6tlh                                  1/1     Running   0          15m
consul-client-sr7jn                                  1/1     Running   0          14m
consul-client-wdskv                                  1/1     Running   0          15m
consul-server-0                                      1/1     Running   0          13m
consul-server-1                                      1/1     Running   0          14m
consul-server-2                                      1/1     Running   0          15m
cortx-control-7c7775dc87-5crbr                       1/1     Running   0          12m
cortx-data-ssc-vm-g2-rhev4-3081-69676457fd-zkx4h     3/3     Running   0          11m
cortx-data-ssc-vm-g2-rhev4-3082-7fd8f84585-pvqvw     3/3     Running   0          11m
cortx-data-ssc-vm-g2-rhev4-3083-7d9f4b5c76-s9h4g     3/3     Running   0          11m
cortx-ha-5d5446d4cc-q4cpm                            3/3     Running   0          3m55s
cortx-server-ssc-vm-g2-rhev4-3081-85f774b67d-8mvfn   2/2     Running   0          9m35s
cortx-server-ssc-vm-g2-rhev4-3082-5d9787698b-4lpmv   2/2     Running   0          9m35s
cortx-server-ssc-vm-g2-rhev4-3083-8475b97884-2std9   2/2     Running   0          9m34s
kafka-0                                              1/1     Running   0          15m
kafka-1                                              1/1     Running   0          15m
kafka-2                                              1/1     Running   0          15m
zookeeper-0                                          1/1     Running   0          15m
zookeeper-1                                          1/1     Running   0          15m
zookeeper-2                                          1/1     Running   0          15m

**Pull request merged**
