### PR TITLE
Updated default value of bool variables to false in cluster.json & node.json

### PR DESCRIPTION
**Pull request by lakshita-jain**
# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by tanujashinde0405 — APPROVED** [review]

**Review by 83bhp — APPROVED** [review]

**Comment by 83bhp** [comment]
retest this please

**Comment by lakshita-jain** [comment]
**Cortx-deployment successful** using custom build: [http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/centos-7.9.2009/custom-build-2413/](url)
**Deployment result** : [http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/centos-7.9.2009/custom-build-2413/](url)

**Comment by lakshita-jain** [comment]
**3 Node VM Deployment Successful using custom build** :[http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/centos-7.9.2009/custom-build-2413/](url)
**Deployment Result** : [http://eos-jenkins.colo.seagate.com/job/Cortx-Deployment/job/VM-Deployment-3Node-CentOS-7.9/310/](url)

**Comment by 83bhp** [comment]
retest this please

**Pull request merged**
