### PR TITLE
EOS-14924: when stonith is down, it will never come back online without manual intervention

### PR DESCRIPTION
**Pull request by knekrasov**
Solution: add failure-timeout=15s for both stonith resources so even
stonith resource fails to start (e.g. due to cable issue), in 15 seconds
Pacemaker will try to launch it again.

### CODE REVIEW

**Review by andkononykhin2 — APPROVED** [review]

**Review by azheregelya — APPROVED** [review]
Looks correct.

**Comment by ypise** [comment]
@knekrasov 
Please resolve conflicts.

**Comment by knekrasov** [comment]
@ypise I've rebased against `pre-cortx-1.0` and resolved conflicts. Thanks!

**Review by ypise — APPROVED** [review]

**Comment by knekrasov** [comment]
@ypise I think I saw this PR merged but I can see it is open again now. What is the current status? Is there anything I can help with to get it merged?

**Pull request merged**
