### PR TITLE
Eos 24986: Adding code for VM support for secret encryption

### PR DESCRIPTION
**Pull request by kailashyadav11**
# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [x] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by nitin-seagate — CHANGES_REQUESTED** [review]
Can we have password something like:
Seagate@123
Add new line at the end of Secret Files

**Comment by kailashyadav11** [comment]
> Can we have password something like:
> Seagate@123
> Add new line at the end of Secret Files

Added the new line
changed the password

**Review by 83bhp — APPROVED** [review]

**Review by tanujashinde0405 — APPROVED** [review]
LGTM

**Pull request merged**
