### PR TITLE
Cortx 30254: Codacy issues fix

### PR DESCRIPTION
**Pull request by lakshita-jain**
# Problem Statement

*   Codacy fix in two shell scripts (i.e. /jenkins/docker/build.sh & jenkins/build.sh)

# Design

*   For Bug, Describe the fix here.
*   For Feature, Post the link for design

# Coding

Checklist for Author

*   \[x] Coding conventions are followed and code is consistent

# Testing

Checklist for Author

*   \[x] Unit and System Tests are added
*   \[x] Test Cases cover Happy Path, Non-Happy Path and Scalability
*   \[x] Testing was performed with RPM

# Impact Analysis

Checklist for Author/Reviewer/GateKeeper

*   \[x] Interface change (if any) are documented
*   \[ ] Side effects on other features (deployment/upgrade)
*   \[ ] Dependencies on other component(s)

# Review Checklist

Checklist for Author

*   \[x] JIRA number/GitHub Issue added to PR
*   \[x] PR is self reviewed
*   \[x] Jira and state/status is updated and JIRA is updated with PR link
*   \[x] Check if the description is clear and explained

# Documentation

Checklist for Author

*   \[x] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by tanujashinde0405 — APPROVED** [review]

**Review by nitin-seagate — APPROVED** [review]
LGTM

**Comment by lakshita-jain** [comment]
Retest this Please

**Comment by lakshita-jain** [comment]
Retest this please

**Comment by gauravchaudhari02** [comment]
retest this please

**Comment by lakshita-jain** [comment]
3 N deployment successful:
https://eos-jenkins.colo.seagate.com/job/Provisioner/job/N-Node_CORTX_Deployment_on_K8s_Cluster/223/console

**Pull request merged**
