### PR TITLE
Main candidate 180521

### PR DESCRIPTION
**Pull request by ypise**
Signed-off-by: Yashodhan Pise yashodhan.pise@seagate.com

-----------------------------------------------------------------------------------------------------------------
Commits for main merge (in reverse chronological order):
- Revert "EOS-19468: USL_Setup Integration (#1246)"
- [EOS-20716] fix service check command (#1279)
- Update network_config and node_init commands (#1280)
- [cortx_setup] initial framework for cortx_setup (#1277)
- Codacy issues missed in PR #1247 (#1278)
- EOS-19898: LR node stamping (#1247)
- EOS-20529: Implement wrappers over CORTX services start/stop to be called later as part of SW upgrade logic (#1270)
- EOS-20430: ISO query API - get CORTX SW upgrade version info (#1249)
- EOS-20427: SW Upgrade pre validation - cluster is healthy (#1269)
- Address- EOS-20437: Configure Network and EOS-20438: Factory Node Initialize (#1244)
- EOS-20627:destroy api does not remove uds packages (#1275)
- Updating r2.md file for sprint-43 (#1276)
- Remove checkpoint flags for statsd and nodejs during teardown (#1271)
- Fixing cortx-ha execution in deploy_vm file and fetching mgmt gateway from grains (#1274)
- EOS_20601: Update Salt configuration files to avoid timeout & minion connectivity issues. (#1250)    
- [cortx-ha-sequence] run cortx-ha sequentially on secondaries (#1243)
- EOS-20506: cluster-id setup file in all nodes (#1230)
- [EOS-20439] split setup provisioner command into granular one's (#1235)
- [EOS-20439] Service user provisioner CLI (#1240)
- EOS-19468: USL_Setup Integration (#1246)
- EOS-19185: remove links to internal sites. (#1252)
- EOS-20503: Disable 2GB swap on LR nodes (#1268)
- EOS-20563: Addition of Management VIP to Deploy jobs (#1242)

-----
[View rendered Cortx-ProvisionerQuickstartGuide.md](https://github.com/Seagate/cortx-prvsnr/blob/main-candidate-180521/Cortx-ProvisionerQuickstartGuide.md)

### CODE REVIEW

**Review by mazinamdar — APPROVED** [review]

**Review by 83bhp — APPROVED** [review]

**Comment by gowthamchinna** [comment]
test this please

**Comment by gowthamchinna** [comment]
test this please

**Comment by ypise** [comment]
test this please

**Comment by ypise** [comment]
Landing blocked due to a cortx-py-utils error from CSM code:
```
23:31:12       provisioner.errors.SaltCmdResultError: salt command failed, reason {
23:31:12              srvnode-1: {
23:31:12          "cmd_|-Stage - Post Install CSM_|-__slot__:salt:setup_conf.conf_cmd('/opt/seagate/cortx/csm/conf/setup.yaml', 'csm:post_install')_|-run": {
23:31:12              "comment": "Command \"/opt/seagate/cortx/csm/bin/csm_setup post_install --config json:///opt/seagate/cortx_configs/provisioner_cluster.json\" run",
23:31:12              "changes": {
23:31:12                  "pid": 29163,
23:31:12                  "retcode": 1,
23:31:12                  "stdout": "",
23:31:12                  "stderr": "Traceback (most recent call last):
23:31:12        File \"/opt/seagate/cortx/csm/bin/csm_setup\", line 74, in <module>
23:31:12          from csm.cli.command import CommandParser
23:31:12        File \"/opt/seagate/cortx/csm/bin/../../csm/cli/command.py\", line 26, in <module>
23:31:12          from csm.common.errors import CSM_OPERATION_SUCESSFUL
23:31:12        File \"/opt/seagate/cortx/csm/bin/../../csm/common/errors.py\", line 18, in <module>
23:31:12          from cortx.utils.errors import BaseError
23:31:12      ImportError: cannot import name 'BaseError'"
23:31:12              }
23:31:12          }
23:31:12      },
```

Awaiting landing for https://github.com/Seagate/cortx-utils/pull/304/files

CC: @priyankdal , @kupranay

**Comment by ypise** [comment]
please test this

**Comment by ypise** [comment]
test this please

**Pull request merged**
