### PR TITLE
Stable candidate 110521

### PR DESCRIPTION
**Pull request by ypise**

### CODE REVIEW

**Comment by ypise** [comment]
test this please

**Comment by ypise** [comment]
test this please

**Review by nitin-seagate — APPROVED** [review]
LGTM

**Comment by ypise** [comment]
The merged was enabled based on http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Provisioner/145/
For mini-provisioner and for http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Provisioner/146/ the jobs failed due to VM infra issues.

**Pull request merged**
