### PR TITLE
EOS-17486:Remove s3iamcli installation from s3server.install (#883)

### PR DESCRIPTION
**Pull request by sradhanand-pati**
* EOS-17486:Remove s3iamcli installation from s3server.install

Signed-off-by: sradhanandpati <sradhanand.pati@seagate.com>

* Removing s3iamcli from teardown

Signed-off-by: sradhanandpati <sradhanand.pati@seagate.com>

### CODE REVIEW

**Review by nitin-seagate — APPROVED** [review]
Please rebase your changes before commit changes

**Comment by nitin-seagate** [comment]
Please rebase your PR, before merging into main

**Review by andkononykhin2 — CHANGES_REQUESTED** [review]
@sradhanand-pati Generally I am ok with the changes but the PR is not ready for the merge:
- DCO fails
- many unrelated changes

Please fix that and then it might be reviewed properly.

**Comment by ypise** [comment]
This is not how we merge.

**Pull request closed without merging**
